### PR TITLE
feat: implement sign out by disabling fast login

### PR DESCRIPTION
**Pull request by michaellee8**
should not be merged before https://github.com/torusresearch/openlogin-sdk-frontend/pull/9

### CODE REVIEW

**Review by phuctm97 — CHANGES_REQUESTED** [review]
Great PR, I think `signout` should be `signOut` instead. Also please add this link to the sign out function comments in case they don't know what fastLogin is: https://docs.tor.us/open-login/api-reference/usage#login

**Comment by michaellee8** [comment]
@phuctm97 Agreed, actually i feels like start should be signIn as well, but changing it now will break existing APIs.

**Comment by phuctm97** [comment]
> @phuctm97 Agreed, actually i feels like start should be signIn as well, but changing it now will break existing APIs.

FYI, `start` was inspired by `Auth0` library.

**Review by phuctm97 — APPROVED** [review]
lgtm

**Pull request merged**
